### ISSUE TITLE
New BG grants section

### ISSUE THREAD

**Issue by andrealbiac** [BuidlGuidl/buidlguidl.com#26]
Sharing an idea/proposal for the BG grants section for the landing page. It's essentially a CTA, same design that we're using in other places for announcing the grants. Some notes on it:

- Check if we like that paragraph text (it's the main intro text we're using everywhere)
- We also discussed if it would make sense to merge all funding sections in one and talk about: streams, cohorts and grants all at once, but I think we agreed that we were gonna keep them separate so they can shine a bit more.
- I'll correct text spacing cause it looks a bit weird now

<img width="812" alt="Captura de pantalla 2024-04-17 a las 16 29 40" src="https://github.com/BuidlGuidl/buidlguidl.com/assets/137904915/53c4cc90-a08e-4715-84f1-31cb161a9a91">
<img width="1056" alt="Captura de pantalla 2024-04-17 a las 16 37 34" src="https://github.com/BuidlGuidl/buidlguidl.com/assets/137904915/49e1067d-8964-4e79-adea-c1aba88af09d">

**Comment by Pabl0cks** [comment]
Merged!
