### ISSUE TITLE
Fetch batch data from bg app API when it is available

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/buidlguidl.com#47]
The batch data from `/batches` was set manually, we'll need to update to to fetch data dinamically when the API is ready

**Comment by carletex** [comment]
Referencing here the PR https://github.com/scaffold-eth/buidlguidl-v3/pull/116 (we'd try to get it merged tomorrow)

We might need to iterate a bit and add some missing data (people count), but it should be quick and can be done in a second PR as we connect this to it.
